# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Trinitarian Logic
subtitle: A Study of Geach's Relative Identity
author: Frank Hubeny
copyright: "2024"
email: frankhubeny@protonmail.com
license: CC-BY-4.0
keywords: trinity, logic, relative identity, absolute identity, identity
logo: ""

# Force re-execution of notebooks on each build.  Auto: only when changed.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: auto

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - Trinity.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/FrankHubeny/TrinitarianLogicgit/ # Online location of your book
  path_to_book: _build/html  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  
# Abbreviations
abbreviations:
  ABR: Associates for Biblical Research
  CMI: Creation Ministries International
  
# Miscellaneous configuration
math:
  # Note the 'single quotes'
  '\dobs': '\mathbf{d}_\text{obs}'
numbering:
  heading_2: true
  heading_3: true

# only_build_toc_files: true
sphinx:
  extra_extensions:
    - sphinx_exercise
    - sphinx_proof
    - sphinx_inline_tabs
    - sphinx_tippy
    - myst_parser
  config:
    html_show_copyright: false
    html_extra_path: ['files']

    myst_enable_extensions: 
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution
    
