site_name: RealPy

theme:
  name: "material"

plugins:
  - mkdocstrings
  
nav:
  - RealPy Docs: index.md
  - Tutorials: tutorials.md
  - How-To Guides: how-to-guides.md
  - Reference: reference.md
  - Explanation: explanation.md
